version: '3'
services:
  web:
    build: .
    ports:
      - '5555:5555'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  mongo_seed:
    container_name: mongo_seed
    build: ./mongo-seed
    depends_on:
      - mongo
